### ISSUE TITLE
input dimension

### ISSUE THREAD

**Issue by zeydabadi** [S-Driscoll/Projection-pursuit#2]
Hi,

I am running your python code `[T, V, PPOUT] = projpursuit.projpursuit(X=X_train, P=2, GUESS=1000)`.
Here X_train has 10000 rows and 30 columns so T has 10000 rows and 2 columns.
I wonder how I can use T for creating a scatter plot that possibly shows different classes?

**Comment by S-Driscoll** [comment]
Hi @zeydabadi, the rows of T correspond to the coordinates of the sample in the subspace found by projection pursuit. So, you can just scatter the pairs T[:,0],T[:,1]. 

```
import matplotlib.pyplot as plt 
plt.scatter(T[:,0],T[:,1])
```
